---
- name: Rainbond | Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Rainbond | Include overrides specific to RHEL 7.
  include_vars: RedHat-7.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == "7"

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure nfs is running.
  service: "name={{ nfs_server_daemon }} state=started enabled=yes"

