---
- hosts: new-master
  roles:
    - { role: rainvar, tags: default }
    - { role: prepare, tags: prepare }
    - { role: docker, tags: docker }
    - { role: kube-master, tags: kube-master }
    - { role: etcd, tags: etcd }
    - { role: lb, tags: lb }
    - { role: health, tags: health }
    - { role: network_plugin/calico, when: "CLUSTER_NETWORK == 'calico'" }
    - { role: network_plugin/flannel, when: "CLUSTER_NETWORK == 'flannel'" }
    - { role: storage/nfs/client, when: "storage_type == 'nfs'" }
    - { role: master, tags: master }
    - { role: node, tags: node }
