---
- name: check nfs server
  stat: path="/grdata/kubernetes/kube-proxy.kubeconfig"
  register: check_server

- shell: if [ -z "$nfsoptions" ]; then  echo rw; else echo $nfsoptions; fi
  register: _nfsopts
  sudo: false
  connection: local

- name: configure /etc/fstab on clients
  action: mount name={{nfsmount}} src={{nfsserver}}:{{nfspath}} fstype=nfs opts={{_nfsopts.stdout}} state=mounted
  when: check_server.stat.isreg is not defined