---
- name: Rainbond | Install ansible Online
  shell: "pip install ansible"
  when: install_type == "online"

- name: Rainbond | Install ansible Offline
  shell: "yum install -y sshpass python-pip ansible"
  when: install_type != "online"

- name: Storage | check init 
  stat: path=/tmp/.grdata.share
  register: check_manage_share

- name: Rainbond | Add share
  template:
    src: share.sh.j2
    dest: /tmp/share.sh
    mode: 0777
  when: check_manage_share.stat.isreg is not defined

- name: Rainbond | Run share
  shell: bash /tmp/share.sh
  when: check_manage_share.stat.isreg is not defined