---
- name: Check | Check if base.image.tgz is download
  stat: path=/grdata/services/offline/base.images.tgz
  register: check_image_base_tgz_download

- name: The next task may take some time to execute
  debug:
    msg: "The next task may take some time to execute: Waiting downloading base.images.tgz (1.5GB)"
  when: check_image_base_tgz_download.stat.isreg is not defined

- name: Rainbond | Download base image tgz ok
  get_url:
    url: http://rainbond-pkg.oss-cn-shanghai.aliyuncs.com/offline/5.0/base.images.2019-01-25-5.0.3.tgz
    dest: /grdata/services/offline/base.images.tgz
  when: check_image_base_tgz_download.stat.isreg is not defined

- name: Check | Check if rainbond.image.tgz is download
  stat: path=/grdata/services/offline/rainbond.images.tgz
  register: check_image_rainbond_tgz_download

- name: The next task may take some time to execute
  debug:
    msg: "The next task may take some time to execute: Waiting downloading rainbond.images.tgz (300MB)"
  when: check_image_rainbond_tgz_download.stat.isreg is not defined

- name: Rainbond | Download rainbond image tgz ok
  get_url:
    url: http://rainbond-pkg.oss-cn-shanghai.aliyuncs.com/offline/5.0/rainbond.images.2019-01-25-5.0.3.tgz
    dest: /grdata/services/offline/rainbond.images.tgz
  when: check_image_rainbond_tgz_download.stat.isreg is not defined